### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [7]:
# np.array  1D : vector
import numpy as np

a = np.array([1,2,3])
print(a)

print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
# 2D : metrix
b = np.array( [[1,2,3],[4,5,6]] )
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3D: tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype=float)
print(c)

[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [4]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [12]:
# np.arange  same as range built in function
np.arange(1,11,2)
print(np.arange(1,11,2))
print(type(np.arange(1,11,2)))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [11]:
# with reshape
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
# with reshape 4D
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [14]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# np.random
np.random.random((3,4))

array([[0.70844257, 0.08117856, 0.13785716, 0.37144933],
       [0.44304579, 0.23902154, 0.06717723, 0.68112726],
       [0.95001288, 0.28791801, 0.6511089 , 0.98613625]])

In [17]:
# np.linspace : generate points start and end, equal dist  (linearly saperable)
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [18]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [19]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
# ndim : number of dimension
a3.ndim

3

In [22]:
# shape : number of rows and cols
print(a3.shape)  # (no of array, row, cols)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
# size : number of items
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [27]:
# itemsize : each items takes size of memory bits
a3.itemsize

8

In [29]:
# dtype  : items ka data types
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [30]:
# astype : to change data type use astype(new_data_type) (used for space reduce purpose)
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [32]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
# scalar operations

# arithmetic
a1 ** 2  # power of 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [35]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [37]:
a2[a2 != 15]

array([12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23])

In [38]:
a2[a2 == 15]

array([15])

In [39]:
# vector operations : array should be  same dimension
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [40]:
np.random.random((3,3))


array([[0.54526413, 0.03078301, 0.27998545],
       [0.39527907, 0.51667226, 0.94997762],
       [0.00638537, 0.90726723, 0.5318025 ]])

In [43]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[52., 82., 54.],
       [31.,  8., 53.],
       [84., 21., 75.]])

## https://numpy.org/doc/stable/user/whatisnumpy.html

In [46]:
# max/min/sum/prod
# axis : 0 -> col and 1 -> row
np.max(a1,axis=1)
np.max(a1,axis=0)
np.prod(a1,axis=0)

array([135408.,  13776., 214650.])

In [49]:
(52+82+ 54)/3

62.666666666666664

In [47]:
# Statistical Operation:  mean/median/std/var
print(np.mean(a1,axis=1))
print(np.median(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))

[62.66666667 30.66666667 60.        ]
[54. 31. 75.]
[13.69509239 18.37268504 27.82085549]
[187.55555556 337.55555556 774.        ]


In [50]:
# trigonomoetric functions : sin, cos, tan....
np.sin(a1)

array([[ 0.98662759,  0.31322878, -0.55878905],
       [-0.40403765,  0.98935825,  0.39592515],
       [ 0.73319032,  0.83665564, -0.38778164]])

In [52]:
# dot product : condition : ( a1.cols==a2.rows and a1.row==a2.cols )
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [53]:
# log and exponents
np.exp(a1)

array([[3.83100800e+22, 4.09399696e+35, 2.83075330e+23],
       [2.90488497e+13, 2.98095799e+03, 1.04137594e+23],
       [3.02507732e+36, 1.31881573e+09, 3.73324200e+32]])

In [55]:
# log and exponents
np.log(a1)  

array([[3.95124372, 4.40671925, 3.98898405],
       [3.4339872 , 2.07944154, 3.97029191],
       [4.4308168 , 3.04452244, 4.31748811]])

In [58]:
# round/floor/ceil
print(np.round(2.876))  # round the float number
print(np.floor(2.876))  # previous int number 
print(np.ceil(2.876))   # next int number
print(np.ceil(np.random.random((2,3))*100))

3.0
2.0
3.0
[[97. 90. 77.]
 [64.  1. 45.]]


### Indexing and Slicing : fetch items from array (indexing)

In [59]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1[0]

0

In [61]:
a1[-2]

8

In [63]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a2[1,0]

4

In [65]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [66]:
a3[1,0,1]

5

In [67]:
a3[0,1,1]

3

In [68]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## slicing : fetch multiple items

In [71]:
a1[2:4:1]

array([2, 3])

In [70]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a2[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [79]:
a2[1,::3]

array([4, 7])

In [73]:
a2[:,2]

array([ 2,  6, 10])

In [74]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [75]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [77]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [83]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [91]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [88]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [87]:
a3[1,:,1]

array([10, 13, 16])

In [86]:
a3[0,1,:]

array([3, 4, 5])

In [85]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [93]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [94]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [96]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [98]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [99]:
# reshape
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [102]:
# ravel : convert to 1D array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [104]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [106]:
np.hstack((a4,a5))  # horizontal stack

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [107]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting  : cut horizontal/verticle

In [108]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [111]:
np.hsplit(a4,2)[0]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [112]:
np.hsplit(a4,2)[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
# vertical splitting

In [113]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [115]:
np.vsplit(a5,3)


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [116]:
np.vsplit(a5,3)[2]

array([[20, 21, 22, 23]])