### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 4, 77, 53, 95],
       [94, 47, 38, 69],
       [59, 73, 63, 81],
       [77, 96, 20, 23],
       [37, 82, 38, 92],
       [60, 20, 45, 43]])

In [7]:
np.sort(a)

array([26, 34, 40, 48, 51, 51, 60, 62, 67, 71, 72, 79, 84, 87, 87])

In [6]:
# reverse [::-1]

np.sort(a)[::-1]

array([87, 87, 84, 79, 72, 71, 67, 62, 60, 51, 51, 48, 40, 34, 26])

In [4]:
# axis=1 : row wise sorting

np.sort(b, axis=1)

array([[ 4, 53, 77, 95],
       [38, 47, 69, 94],
       [59, 63, 73, 81],
       [20, 23, 77, 96],
       [37, 38, 82, 92],
       [20, 43, 45, 60]])

In [5]:
# axis=0 : column wise sorting

np.sort(b,axis=0)

array([[ 4, 20, 20, 23],
       [37, 47, 38, 43],
       [59, 73, 38, 69],
       [60, 77, 45, 81],
       [77, 82, 53, 92],
       [94, 96, 63, 95]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [10]:
# 1D array
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [9]:
# code
np.append(a,200)

array([ 26,  62,  84,  87,  79,  34,  40,  60,  71,  67,  72,  51,  51,
        48,  87, 200])

In [12]:
# 2D array
b

array([[ 4, 77, 53, 95],
       [94, 47, 38, 69],
       [59, 73, 63, 81],
       [77, 96, 20, 23],
       [37, 82, 38, 92],
       [60, 20, 45, 43]])

In [13]:
np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[ 4.        , 77.        , 53.        , 95.        ,  0.53689183],
       [94.        , 47.        , 38.        , 69.        ,  0.38777133],
       [59.        , 73.        , 63.        , 81.        ,  0.7723689 ],
       [77.        , 96.        , 20.        , 23.        ,  0.4933702 ],
       [37.        , 82.        , 38.        , 92.        ,  0.95166254],
       [60.        , 20.        , 45.        , 43.        ,  0.19146875]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [14]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d), axis=0)   # axis=0 row wise concatenate

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d), axis=1)   # axis=1 column wise concatenate

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [19]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [20]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [21]:
# code
c

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
np.expand_dims(c,axis=0)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [22]:
np.expand_dims(c,axis=0).shape

(1, 2, 3)

In [25]:
np.expand_dims(c,axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [23]:
np.expand_dims(c,axis=2).shape

(2, 3, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [26]:
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [28]:
# find all indices (index Position ) with value greater than 50
np.where(a>50)

(array([ 1,  2,  3,  4,  7,  8,  9, 10, 11, 12, 14]),)

In [30]:
# replace all values > 50 with 0
np.where(a>50,False, True)

array([ True, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True, False])

In [29]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([26,  0,  0,  0,  0, 34, 40,  0,  0,  0,  0,  0,  0, 48,  0])

In [31]:
np.where(a%2 == 0, 0, a)

array([ 0,  0,  0, 87, 79,  0,  0,  0, 71, 67,  0, 51, 51,  0, 87])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [32]:
# code
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [33]:
# max item index position np.agrmax()
np.argmax(a)

3

In [34]:
b

array([[ 4, 77, 53, 95],
       [94, 47, 38, 69],
       [59, 73, 63, 81],
       [77, 96, 20, 23],
       [37, 82, 38, 92],
       [60, 20, 45, 43]])

In [35]:
np.argmax(b,axis=0)  # 0 :row

array([1, 3, 2, 0])

In [ ]:
np.argmax(b,axis=1)   # 1 : col

array([1, 3, 1, 3, 1, 1])

In [36]:
# np.argmin
np.argmin(a)

0

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [37]:
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [41]:
# cumulative sum
np.cumsum(a)

array([ 26,  88, 172, 259, 338, 372, 412, 472, 543, 610, 682, 733, 784,
       832, 919])

In [40]:
b

array([[ 4, 77, 53, 95],
       [94, 47, 38, 69],
       [59, 73, 63, 81],
       [77, 96, 20, 23],
       [37, 82, 38, 92],
       [60, 20, 45, 43]])

In [42]:
np.cumsum(b,axis=1)  # 1 : row wise

array([[  4,  81, 134, 229],
       [ 94, 141, 179, 248],
       [ 59, 132, 195, 276],
       [ 77, 173, 193, 216],
       [ 37, 119, 157, 249],
       [ 60,  80, 125, 168]])

In [43]:
np.cumsum(b,axis=0)  # 1 : col wise

array([[  4,  77,  53,  95],
       [ 98, 124,  91, 164],
       [157, 197, 154, 245],
       [234, 293, 174, 268],
       [271, 375, 212, 360],
       [331, 395, 257, 403]])

In [38]:
np.cumsum(b)  # if axis not given in np.cumsum() then it convert array 2D -> 1D and after perform np.cumsum()

array([   4,   81,  134,  229,  323,  370,  408,  477,  536,  609,  672,
        753,  830,  926,  946,  969, 1006, 1088, 1126, 1218, 1278, 1298,
       1343, 1386])

In [44]:
# np.cumprod
np.cumprod(a)

array([                  26,                 1612,               135408,
                   11780496,            930659184,          31642412256,
              1265696490240,       75941789414400,     5391867048422400,
         361255092244300800,  7563622567880105984, -1636874586015178752,
        8753116481773641728, -4125522570184884224, -8432326205603446784])

In [45]:
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [46]:
np.cumprod(a)

array([                  26,                 1612,               135408,
                   11780496,            930659184,          31642412256,
              1265696490240,       75941789414400,     5391867048422400,
         361255092244300800,  7563622567880105984, -1636874586015178752,
        8753116481773641728, -4125522570184884224, -8432326205603446784])

In [51]:
# find fact using np.cumprod()
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [50]:
np.cumprod(np.arange(1,6))

array([  1,   2,   6,  24, 120])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [52]:
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [55]:
# 100 percentile : max
# 0 percentile : min
# 50 percentile : median

np.percentile(a,50)

62.0

In [54]:
np.median(a)

62.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [57]:
# code
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [58]:
# frequency count

np.histogram(a,bins=[0,50,100])

(array([ 4, 11]), array([  0,  50, 100]))

In [59]:
np.histogram(a, bins=10)

(array([1, 1, 1, 1, 2, 2, 1, 2, 1, 3]),
 array([26. , 32.1, 38.2, 44.3, 50.4, 56.5, 62.6, 68.7, 74.8, 80.9, 87. ]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [60]:
# corelation range [-1, 1]


salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [61]:
# code
a


array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [63]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a, items)  # check given list of items present in list which are present in given array or not 


array([False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False])

In [65]:
# search multiple items in Array : np.isin
a[ np.isin(a, items) ]

array([40, 60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [66]:
# code
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [67]:
np.flip(a)

array([87, 48, 51, 51, 72, 67, 71, 60, 40, 34, 79, 87, 84, 62, 26])

In [68]:
b

array([[ 4, 77, 53, 95],
       [94, 47, 38, 69],
       [59, 73, 63, 81],
       [77, 96, 20, 23],
       [37, 82, 38, 92],
       [60, 20, 45, 43]])

In [69]:
np.flip(b,axis=1)   # 1 : flip in row

array([[95, 53, 77,  4],
       [69, 38, 47, 94],
       [81, 63, 73, 59],
       [23, 20, 96, 77],
       [92, 38, 82, 37],
       [43, 45, 20, 60]])

In [70]:
np.flip(b,axis=0)  # 0 : flip in columns

array([[60, 20, 45, 43],
       [37, 82, 38, 92],
       [77, 96, 20, 23],
       [59, 73, 63, 81],
       [94, 47, 38, 69],
       [ 4, 77, 53, 95]])

In [71]:
np.flip(b)   # both flip done at same time 

array([[43, 45, 20, 60],
       [92, 38, 82, 37],
       [23, 20, 96, 77],
       [81, 63, 73, 59],
       [69, 38, 47, 94],
       [95, 53, 77,  4]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [72]:
# code
a

array([26, 62, 84, 87, 79, 34, 40, 60, 71, 67, 72, 51, 51, 48, 87])

In [73]:
np.put(a,[0,1],[110,530])  # change permently at same time multiple items

In [74]:
a

array([110, 530,  84,  87,  79,  34,  40,  60,  71,  67,  72,  51,  51,
        48,  87])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [76]:
# code
a 

array([110, 530,  84,  87,  79,  34,  40,  60,  71,  67,  72,  51,  51,
        48,  87])

In [79]:
np.delete(a,0)  # not perment change

array([530,  84,  87,  79,  34,  40,  60,  71,  67,  72,  51,  51,  48,
        87])

In [78]:
np.delete(a,[0,2,4])

array([530,  87,  34,  40,  60,  71,  67,  72,  51,  51,  48,  87])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [81]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [82]:
np.intersect1d(m,n)

array([3, 4, 5])

In [83]:
np.setdiff1d(n,m)

array([6, 7])

In [84]:
np.setdiff1d(m,n)

array([1, 2])

In [86]:
np.setxor1d(m,n)  # remove common items

array([1, 2, 6, 7])

In [87]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [ ]:
m[ np.in1d(m,1) ]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [88]:
# code
a

array([110, 530,  84,  87,  79,  34,  40,  60,  71,  67,  72,  51,  51,
        48,  87])

In [89]:
np.clip(a,a_min=25, a_max=75)

array([75, 75, 75, 75, 75, 34, 40, 60, 71, 67, 72, 51, 51, 48, 75])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals

In [ ]:
x = np.array([[1,2,3]])

In [ ]:
x.shape

(1, 3)

In [ ]:
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [ ]:
y = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
y

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
y.shape

(2, 2, 2)

In [ ]:
np.swapaxes(y,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
np.random.uniform(-1,0,1000)

array([-0.08728094, -0.7483751 , -0.6123448 , -0.4475416 , -0.49006559,
       -0.036897  , -0.92936409, -0.77499691, -0.6956266 , -0.85905663,
       -0.89635923, -0.85540065, -0.1641403 , -0.37388343, -0.48776189,
       -0.21526849, -0.82137585, -0.91063506, -0.24677121, -0.96342324,
       -0.30932901, -0.55554639, -0.76527232, -0.7502086 , -0.37548202,
       -0.0664378 , -0.30131816, -0.49111156, -0.77890389, -0.55340055,
       -0.56145984, -0.46311454, -0.08162521, -0.36223126, -0.67972628,
       -0.34598587, -0.65619689, -0.896009  , -0.06088222, -0.16234861,
       -0.62816625, -0.42282818, -0.52282208, -0.9556742 , -0.4530181 ,
       -0.87220948, -0.39626115, -0.23724638, -0.5160289 , -0.16166277,
       -0.19454709, -0.77754351, -0.24182469, -0.77252038, -0.81283591,
       -0.17918819, -0.76632387, -0.32939307, -0.98202359, -0.17347179,
       -0.54867583, -0.70445237, -0.99476256, -0.11063956, -0.69124513,
       -0.53199972, -0.74651087, -0.38532708, -0.71479522, -0.01